[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm config set onlyBuiltDependencies '[\"@prisma/client\", \"@prisma/engines\", \"bcrypt\", \"prisma\"]' --location project",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm prisma generate", "pnpm build"]

[start]
cmd = "pnpm start:prod"
