[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile --allow-build=bcrypt --allow-build=@prisma/client --allow-build=@prisma/engines --allow-build=prisma"]

[phases.build]
cmds = ["pnpm prisma generate", "pnpm build"]

[start]
cmd = "pnpm start:prod"
